# Generated by Django 3.2.9 on 2022-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='newsletter',
            field=models.TextField(default=0),
        ),
    ]
