# Generated by Django 3.2.9 on 2022-01-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
