# Generated by Django 3.2.9 on 2021-12-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211203_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
