# Generated by Django 3.2.9 on 2022-01-06 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whislist',
            new_name='Wishlist',
        ),
    ]
